authentication/urls.py
from django.conf.urls import url

from authentication.views import (
    PatientCardDetailView,
    PatientIndexView,
    PatientDetailView,
    DoctorIndexView,
    DoctorDetailView,
)


urlpatterns = [
    url(r'^cards/(?P<pk>\d+)/$', PatientCardDetailView.as_view(), name='card_details'),

    url(r'^doctors/$', DoctorIndexView.as_view(), name='doctor_index'),
    url(r'^doctors/(?P<pk>\d+)/$', DoctorDetailView.as_view(), name='doctor_details'),

    url(r'^patients/$', PatientIndexView.as_view(), name='patient_index'),
    url(r'^patients/(?P<pk>\d+)/$', PatientDetailView.as_view(), name='patient_details'),
]

dcms/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='base.html')),
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('authentication.urls', namespace='users')),
    url(r'^visits/', include('visits.urls', namespace='visits')),
]

visits/urls.py
from django.conf.urls import url

from visits.views import VisitIndexView, VisitDetailView


urlpatterns = [
    url(r'^$', VisitIndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', VisitDetailView.as_view(), name='details'),
]

authentication/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from visits.models import PatientCard


class CustomUser(AbstractUser):
    is_doctor = models.BooleanField(default=False)
    medical_right_number = models.CharField(max_length=16, blank=True)

    pesel = models.CharField(max_length=11, blank=True)
    date_of_birth = models.DateField(blank=True, null=True)

    city = models.CharField(max_length=32, blank=True)
    post_code = models.CharField(max_length=32, blank=True)
    address = models.CharField(max_length=64, blank=True)
    telephone = models.CharField(max_length=12, blank=True)

    def __str__(self):
        return self.get_full_name()

    def get_full_address(self):
        return "{post_code} {city}, {address}".format(
            post_code=self.post_code.strip(" "),
            city=self.city.strip(" "),
            address=self.address.strip(" ")
        )

documents/models.py
from django.conf import settings
from django.db import models


class Document(models.Model):
    created_date = models.DateTimeField()
    description = models.TextField()
    number = models.CharField(max_length=32)
    doctor = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='doctor_%(class)s')
    patient = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='patient_%(class)s')
    visit = models.ForeignKey('visits.Visit', related_name='%(class)s')

    class Meta:
        abstract = True

    def __str__(self):
        return "{}, {}".format(self.number, self.created_date.date())


class Referral(Document):
    pass


class Prescription(Document):
    pass


class Receipt(Document):
    is_invoice = models.BooleanField()
    total_value = models.DecimalField(max_digits=8, decimal_places=2)

schedules/models.py
from django.conf import settings
from django.db import models


class Schedule(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    creator = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='schedules'
    )


class Term(models.Model):
    date = models.DateField()
    starts = models.TimeField()
    ends = models.TimeField()
    is_free = models.BooleanField(default=False)
    schedule = models.ForeignKey(Schedule)

    def __str__(self):
        return "{}, {} - {}".format(
            self.date, self.starts, self.ends
        )

    class Meta:
        ordering = ("-date", "-starts")

visits/models.py
from django.conf import settings
from django.db import models


class PatientCard(models.Model):
    registration_date = models.DateTimeField()
    insurance = models.TextField(max_length=16, blank=True)
    patient = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='my_card')
    main_doctor = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='cards')

    def __str__(self):
        return self.patient.get_full_name()


class Visit(models.Model):
    timestamp = models.DateTimeField()
    reason = models.TextField(blank=True)
    description = models.TextField(blank=True)
    card = models.ForeignKey(PatientCard, related_name='visits')
    doctor = models.ForeignKey(settings.AUTH_USER_MODEL)

    class Meta:
        ordering = ('-timestamp',)

    def __str__(self):
        return "{}".format(self.timestamp.date())

authentication/views.py
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView

from authentication.models import CustomUser
from visits.models import PatientCard


class UserIndexView(ListView):
    template_name = 'authentication/index.html'
    model = CustomUser
    context_object_name = 'people'
    paginate_by = 20
    is_doctor = None

    def get_context_data(self, **kwargs):
        context = super(UserIndexView, self).get_context_data(**kwargs)
        context['is_doctor'] = self.is_doctor
        return context


class PatientCardDetailView(DetailView):
    template_name = 'authentication/card_details.html'
    model = PatientCard
    context_object_name = 'card'


class DoctorIndexView(UserIndexView):
    is_doctor = True
    queryset = CustomUser.objects.filter(
        groups__name__in=["Doctor"]
    )


class DoctorDetailView(DetailView):
    template_name = 'authentication/doctor_details.html'
    model = CustomUser
    context_object_name = 'doctor'
    queryset = CustomUser.objects.filter(
        groups__name__in=["Doctor"]
    )


class PatientIndexView(UserIndexView):
    is_doctor = False
    queryset = CustomUser.objects.filter(
        groups__name__in=["Patient"]
    )


class PatientDetailView(DetailView):
    template_name = 'authentication/patient_details.html'
    model = CustomUser
    context_object_name = 'patient'
    queryset = CustomUser.objects.filter(
        groups__name__in=["Patient"]
    )

visits/views.py
from django.views.generic import ListView, DetailView

from visits.models import Visit
from datetime import datetime, timedelta


class VisitIndexView(ListView):
    template_name = 'visits/index.html'
    model = Visit
    context_object_name = 'past_visits'
    today = datetime.now().date()
    tomorrow = today + timedelta(days=1)
    related = ('doctor', 'card', 'card__patient')
    queryset = Visit.objects.filter(timestamp__lt=today).select_related(*related)
    paginate_by = 20

    def get_context_data(self, **kwargs):
        context = super(VisitIndexView, self).get_context_data(**kwargs)
        context['todays_visits'] = Visit.objects.filter(
            timestamp__range=(self.today, self.tomorrow)
        ).select_related(*self.related)
        context['future_visits'] = Visit.objects.filter(
            timestamp__gt=self.tomorrow
        ).select_related(*self.related)
        return context


class VisitDetailView(DetailView):
    template_name = 'visits/details.html'
    model = Visit
    context_object_name = 'visit'

templates/authentication/card_details.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <div class="page-header">
            <h1>Card details <small> for {{ card.patient }}</small></h1>
        </div>
    </div>

    <div class="container">
        <ul class="nav nav-pills pull-right">
            <li role="presentation"><a href="{% url 'users:patient_details' card.patient.id %}">Patient personal details</a></li>
            <li role="presentation"><a href="{% url 'users:doctor_details' card.main_doctor.id %}">Main doctor</a></li>
        </ul>
    </div>

    <div class="container">
        <h2>Basic information</h2>
        <dl class="dl-horizontal">
            <dt>Patient</dt>
            <dd>{{ card.patient }}</dd>
            <dt>PESEL</dt>
            <dd>{{ card.patient.pesel|default:"none" }}</dd>
            <dt>Registration date</dt>
            <dd>{{ card.registration_date }}</dd>
            <dt>Insurance</dt>
            <dd>{{ card.insurance|default:"none" }}</dd>
            <dt>Main doctor</dt>
            <dd>{{ card.main_doctor }}</dd>
        </dl>
    </div>

    <div class="container">
        <h2>All visits</h2>
        {% if card.visits.all %}
        <ul>
            {% for visit in card.visits.all %}
                <li><a href="{% url 'visits:details' visit.id %}">{{ visit }} - {{ visit.doctor }}</a></li>
            {% endfor %}
        </ul>
        {% else %}
            <p>There are no visits.</p>
        {% endif %}
    </div>

    <div class="container">
        <h2>Documents</h2>
        {% include "documents/list.html" with documents=card.patient.patient_referral.all document_name="referrals" related_name="card" %}
        {% include "documents/list.html" with documents=card.patient.patient_prescription.all document_name="prescriptions" related_name="card" %}
        {% include "documents/list.html" with documents=card.patient.patient_receipt.all document_name="receipts" related_name="card" %}
    </div>

{% endblock %}

templates/authentication/doctor_details.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <div class="page-header">
            <h1>Doctor details <small>{{ doctor }}</small></h1>
        </div>
    </div>

    <div class="container">
        <h2>Personal information</h2>
        <dl class="dl-horizontal">
            <dt>Doctor</dt>
            <dd>{{ doctor }}</dd>
            <dt>PESEL</dt>
            <dd>{{ doctor.pesel|default:"none" }}</dd>
            <dt>Medicat right number</dt>
            <dd>{{ doctor.medical_right_number|default:"none" }}</dd>
            <dt>Date of birth</dt>
            <dd>{{ doctor.date_of_birth }}</dd>
        </dl>

        <h2>Contact details</h2>
        <dl class="dl-horizontal">
            <dt>Email</dt>
            <dd>{{ doctor.email|default:"none" }}</dd>
            <dt>Telephone</dt>
            <dd>{{ doctor.telephone|default:"none" }}</dd>
            <dt>Address</dt>
            <dd>{{ doctor.get_full_address|default:"none" }}</dd>
        </dl>

        <div class="container">
            <h2>All patients</h2>
            {% if doctor.cards.all %}
            <ul>
                {% for card in doctor.cards.all %}
                    <li><a href="{% url 'users:patient_details' card.patient.id %}">{{ card.patient }}</a></li>
                {% endfor %}
            </ul>
            {% else %}
                <p>This doctor doesn't has any patients.</p>
            {% endif %}
        </div>
    </div>

{% endblock %}

templates/authentication/index.html
{% extends "base.html" %}

{% block content %}

    <div class="container">
        <div class="page-header">
            <h1>All {% if is_doctor %}doctors{% else %}patients{% endif %}</h1>
        </div>
    </div>


    <div class="container">
        <table class="table">
            <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>PESEL</th>
                <th>Telephone</th>
                <th>View</th>
            </tr>
            </thead>
            <tbody>
            {% for person in people %}
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{ person }}</td>
                <td>{{ person.pesel }}</td>
                <td>{{ person.telephone }}</td>
                <td><a href="{% if is_doctor %}{% url 'users:doctor_details' person.id %}{% else %}{% url 'users:patient_details' person.id %}{% endif %}">Go to details</a></td>
            </tr>
            {% endfor %}
           </tbody>
        </table>
    </div>

    <nav>
        <ul class="pager">
            {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}">Newer</a></li>
            {% endif %}
            {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}">Older</a></li>
            {% endif %}
        </ul>
    </nav>
    <p class="text-center">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</p>

{% endblock %}

templates/authentication/patient_details.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <div class="page-header">
            <h1>Patient details <small>{{ patient }}</small></h1>
        </div>
    </div>

    <div class="container">
        <ul class="nav nav-pills pull-right">
            <li role="presentation"><a href="{% url 'users:card_details' patient.my_card.id %}">Patient card details</a></li>
        </ul>
    </div>

    <div class="container">
        <h2>Personal information</h2>
        <dl class="dl-horizontal">
            <dt>Patient</dt>
            <dd>{{ patient }}</dd>
            <dt>PESEL</dt>
            <dd>{{ patient.pesel|default:"none" }}</dd>
            <dt>Date of birth</dt>
            <dd>{{ patient.date_of_birth }}</dd>
        </dl>

        <h2>Contact details</h2>
        <dl class="dl-horizontal">
            <dt>Email</dt>
            <dd>{{ patient.email|default:"none" }}</dd>
            <dt>Telephone</dt>
            <dd>{{ patient.telephone|default:"none" }}</dd>
            <dt>Address</dt>
            <dd>{{ patient.get_full_address|default:"none" }}</dd>
        </dl>
    </div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dental Clinic Management System</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

</head>
<body style="padding-top: 50px;">
<div id="wrap">

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Dental Clinic Management System</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li {% if 'visits' in request.path %}class="active"{% endif %}><a href=/visits/>Visits</a></li>
            <li {% if 'schedule' in request.path %}class="active"{% endif %}><a href="/schedule/">Schedule</a></li>
            <li {% if 'patients' in request.path %}class="active"{% endif %}><a href="/users/patients/">Patients</a></li>
            <li {% if 'doctors' in request.path %}class="active"{% endif %}><a href="/users/doctors/">Doctors</a></li>
          </ul>
          <p class="navbar-text navbar-right">
            <a href="{% if user.is_superuser %}/admin/{% endif %}" class="navbar-link">{{ user.get_full_name }}</a>
            <span class="glyphicon glyphicon-user"></span>
            <a href="#"><span class="glyphicon glyphicon-log-out"></span></a>
          </p>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    {% block content %}
      <div class="starter-template" style="padding: 40px 15px; text-align: center;">
        <h1>Welcome in Dental Clinic Management system</h1>
        <p class="lead">Review your planed and completed <a href='/visits/'>visits</a> or go check current <a href="/schedule/">schedule</a>.</p>
      </div>
    {% endblock %}

</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

</body>
</html>

templates/documents/list.html
<h3>Attached {{ document_name }}</h3>
{% if documents %}
    <ul>
        {% for document in documents %}
        <li><a href="#">{{ document }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>There are no {{ document_name }} related to this {{ related_name }}.</p>
{% endif %}

templates/visits/details.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <div class="page-header">
            <h1>Visit details <small>{{ visit.timestamp }}</small></h1>
        </div>
    </div>

    <div class="container">
        <ul class="nav nav-pills pull-right">
            <li role="presentation"><a href="{% url 'users:card_details' visit.card.id %}">Patient card details</a></li>
            <li role="presentation"><a href="{% url 'users:patient_details' visit.card.patient.id %}">Patient personal details</a></li>
        </ul>
    </div>

    <div class="container">
        <h2>Planed visit details</h2>
        <dl class="dl-horizontal">
            <dt>Patient</dt>
            <dd>{{ visit.card.patient }}</dd>
            <dt>PESEL</dt>
            <dd>{{ visit.card.patient.pesel|default:"none" }}</dd>
            <dt>Doctor</dt>
            <dd>{{ visit.doctor }}</dd>
            <dt>Visit date</dt>
            <dd>{{ visit.timestamp }}</dd>
            <dt>Visit reason</dt>
            <dd>{{ visit.reason|default:"none" }}</dd>
        </dl>
    </div>

    <div class="container">
        <h2>Completed visit details</h2>
        <p class="lead">{{ visit.description|default:"Visit hasn't been completed yet." }}</p>
    </div>

    <div class="container">
        <h2>Documents</h2>
        {% include "documents/list.html" with documents=visit.referral.all document_name="referrals" related_name="visit" %}
        {% include "documents/list.html" with documents=visit.prescription.all document_name="prescriptions" related_name="visit" %}
        {% include "documents/list.html" with documents=visit.receipt.all document_name="receipts" related_name="visit" %}
    </div>

{% endblock %}

templates/visits/index.html
{% extends "base.html" %}

{% block content %}

    {% if not page_obj.has_previous %}
        {% include "visits/table.html" with visits=todays_visits title="Today's visits" empty_msg="You don't have any visits scheduled for today." %}
        {% include "visits/table.html" with visits=future_visits title="Future visits" empty_msg="You don't have any future visits." %}
    {% endif %}

    {% include "visits/table.html" with visits=past_visits title="Past visits" empty_msg="You don't have any past visits." %}

    <nav>
        <ul class="pager">
            {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}">Newer</a></li>
            {% endif %}
            {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}">Older</a></li>
            {% endif %}
        </ul>
    </nav>
    <p class="text-center">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</p>

{% endblock %}

templates/visits/table.html
<div class="container">
    <div class="page-header">
        <h1>{{ title }}</h1>
    </div>
    {% if visits %}
        <table class="table">
            <thead>
            <tr>
                <th>#</th>
                <th>Patient</th>
                <th>Doctor</th>
                <th>Date</th>
                <th>Time</th>
                <th>View</th>
            </tr>
            </thead>
            <tbody>
            {% for visit in visits %}
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{ visit.card.patient.get_full_name }}</td>
                <td>{{ visit.doctor.get_full_name }}</td>
                <td>{{ visit.timestamp|date:"d-m-Y" }}</td>
                <td>{{ visit.timestamp|date:"H:m" }}</td>
                <td><a href="{% url 'visits:details' visit.pk %}">Go to details</a></td>
            </tr>
            {% endfor %}
           </tbody>
        </table>
    {% else %}
        <p>{{ empty_msg }}</p>
    {% endif %}
</div>